admin:
  username: admin
  password_hash: $2a$10$s9jQdnpJYe/ZD9aoejkRZOA8QH/pf1l.Kw58K4yPDJTjZR0O2y0/q
  secret: 89a7f6d8e4c3b2a1f5e6d7c8b9a0f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7
  deployCommand: ./deploy.sh
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: true
    categories: true
    tags: true
    ingredients: true
    difficulty: true
    time: true
    servings: true
    calories: true
title: Minhas Receitas
subtitle: Lista de todas as receitas do aplicativo Boil
description: >-
  Nesse blog terá todas as receitas que devem ser listadas no aplicativo e
  deverá tbm ser criada novas por ele.
keywords: Receitas
author: Pablo Galvão
language: pt
timezone: America/Sao_Paulo
url: https://pablopgalvao.github.io
root: /receitas/
permalink: ':day/:month/:year/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: Sem categoria
category_map: null
tag_map: null
meta_generator: true
date_format: DD-MM-YYYY
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
ignore: null
# theme: icarusyy
theme: landscape
deploy:
  type: git
  repo: https://github.com/pablopgalvao/receitas.git
  branch: gh-pages
